### ISSUE TITLE
Status message is Resolving and then again prompt the public key

### ISSUE THREAD

**Issue by slrslr** [ZorrillosDev/watchit-app#108]
Hello,

i have just downloaded
https://github.com/ZorrillosDev/watchit-app/releases/download/v0.2.0-alpha.1/watchit-0.2.0-alpha.1.AppImage
Ran it on my Linux Manjaro, it prompt public key. This was a bit confusing, but i have found it scrolling down the page https://watchitapp.site/

key: QmR9f898E2Y6H4rUqUQkB5g615wht1q4fxCPfZzxA4jXaR

Then it shown bootstrapping, then resolving then returns back to the screen where it prompts the public key.
I have seen no message which would explain why it not connected.

**Comment by geolffreym** [comment]
Hi @slrslr thank you for submit an issue with us. Could u try again please using this key: k2k4r8kghdt2njykw7n5bisp4wgynjhs4gnnh5p1ik2ixqdive47o0oa

About the message: yes, you are rigth. we need add some clear message on that "connectivity issue"

**Comment by slrslr** [comment]
> Could u try again please using this key

yes, this different key (not listed on your site https://watchitapp.site/) worked to show the movies and the movie was played too..

**Comment by geolffreym** [comment]
Glad to hear that buddy :)

**Comment by geolffreym** [comment]
@slrslr this is not exactly an app issue, so we cannot fix it with a PR, this is a connectivity issue solved already. The key in the site is valid.
