### ISSUE TITLE
Exiting while status is closing causes the audio to continue playing anyway

### ISSUE THREAD

**Issue by xamboozi** [ZorrillosDev/watchit-app#124]
I started playing a video and while it was still "connecting" I tried to close it and search for something else. Somehow the video continued to play in the background as I could hear the audio. The only way to stop it is to close the whole app and relaunch,

**Comment by geolffreym** [comment]
Hi @xamboozi thank you for submit an issue . This is happening in the "connecting" after play the movie and try to close in the "X" top button? Then you go back to movie lists and you hear the movie in background, am i right?

**Comment by xamboozi** [comment]
yup - here is a step by step to recreate:

1. launch watchit
2. click a movie
3. click play
4. status says "connecting" and BEFORE the movie actually started playing
5. Immediately hit back
6. sit at the menu of movies and it will begin playing in the background without any way of stopping it
7. You can try to play a different movie, or even the same one again but the audio will continue to play in the background until you exit the app and relaunch

My platform:

Edition	Windows 10 Pro
Version	21H2
Installed on	‎1/‎19/‎2021
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0
