### ISSUE TITLE
The Desktop and Web app aren't working

### ISSUE THREAD

**Issue by Stake2** [ZorrillosDev/watchit-app#132]
They aren't working, I already tried the "Public Domain Movies Key" and also my key.
It says "Bootstraping" and "Resolving" and then comes back to the "Type public key" screen.

**Comment by geolffreym** [comment]
Hi @Stake2 thank your for submit an issue. Are you trying to use web and app release and having issues with both right?

**Comment by Stake2** [comment]
@geolffreym Yes, its with both ones

**Comment by olwe1** [comment]
Hi, I'm stuck on `Bootstrapping` aswell. (AppImage edition)

**Comment by geolffreym** [comment]
Hi @olwe1 are you using some IPFS node already?

**Comment by olwe1** [comment]
Yes exactly

**Comment by geolffreym** [comment]
Ok, got iy @olwe1 probably we have a port conflict. 
Could you check if this ports are not getting used:

```
DEFAULT_API_PORT = 6002
DEFAULT_GATEWAY_PORT = 9090
DEFAULT_SWARM_TCP = 4010
DEFAULT_SWARM_WS = 4011
```

In any case we have a proposal to improve this re-use current node
https://github.com/ZorrillosDev/WEISP/blob/main/SCP/SCP-002.md

**Comment by olwe1** [comment]
No they're not used. Here what I have:
```
tcp   LISTEN 0      128        127.0.0.1:631          0.0.0.0:*    users:(("cupsd",pid=897,fd=9))        
tcp   LISTEN 0      4096       0.0.0.0:4001           0.0.0.0:*    users:(("ipfs",pid=27826,fd=24))      
tcp   LISTEN 0      4096       127.0.0.1:5001       0.0.0.0:*    users:(("ipfs",pid=27826,fd=38))      
tcp   LISTEN 0      4096       127.0.0.1:8080       0.0.0.0:*    users:(("ipfs",pid=27826,fd=40))      
tcp   LISTEN 0      128          [::1]:631                     [::]:*       users:(("cupsd",pid=897,fd=8))        
tcp   LISTEN 0      4096        [::]:4001                     [::]:*       users:(("ipfs",pid=27826,fd=25))
```

**Comment by geolffreym** [comment]
Fixed in https://github.com/ZorrillosDev/watchit-app/releases/tag/v0.3.0-alpha.2.

@Stake2 @olwe1 please use this key for web/desktop `zdpuAm8LAsmLMCabhEetvS7o5ZUMUEWPNmKrfwEnB3H4Zxoir` or IPNS key `QmR9f898E2Y6H4rUqUQkB5g615wht1q4fxCPfZzxA4jXaR` for desktop app.
We are posting new keys for new movies releases in [Matrix Watchit Channel](https://matrix.to/#/#watchit:matrix.org)

Please guys keep us posted. Thank you :)

**Comment by olwe1** [comment]
Unfortunately it's still stucks at `bootstrapping` for me. With `0.3.0-alpha.2` and the new key. With my own IPFS node on and off.

**Comment by geolffreym** [comment]
0.0 could we try please check the logs `export LOG=* && ./watchit-0.3.0-alpha.2.AppImage`

**Comment by geolffreym** [comment]
@olwe1 probably i found the reason why is this happening!!

`Error: lock ~/.ipfs_w/repo.lock: someone else has the lock `

Could you try please removing this directory? I need found a way to tackle this.

**Comment by olwe1** [comment]
I don't have a `repo.lock` in `~/.ipfs_w` but I do have one in `~/.ipfs` and it doesn't change anything when I remove it.
Here's the logs have I have with: `export LOG=* && ./watchit-0.3.0-alpha.2.AppImage`
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[7722:0116/215810.478278:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-01-16T20:58:10.921Z [INFO]  MAIN: Fade in splash done
2022-01-16T20:58:11.977Z [INFO]  CORE: Start orbit..
2022-01-16T20:58:11.977Z [INFO]  NODE: Running ipfs node
2022-01-16T20:58:11.977Z [INFO]  NODE: Setting up node..
2022-01-16T20:58:11.980Z [INFO]  IPFS: Running API on port: 6002
2022-01-16T20:58:11.980Z [INFO]  IPFS: Running Gateway on port: 9090
2022-01-16T20:58:11.980Z [INFO]  IPFS: Swarm TCP listening on port: 4010
2022-01-16T20:58:11.980Z [INFO]  IPFS: Swarm WS listening on port: 4011
2022-01-16T20:58:11.983Z [WARN]  IPFS: Starting node
2022-01-16T20:58:12.324Z [INFO]  MAIN: Fade out splash done!
2022-01-16T20:58:31.988Z [INFO]  IPFS: Forcing start
2022-01-16T20:58:31.990Z [WARN]  IPFS: Starting node
```

**Comment by geolffreym** [comment]
@olwe1 no errors after that log?

**Comment by olwe1** [comment]
Nothing, it's just stuck on `bootstrapping`

**Comment by geolffreym** [comment]
@Stake2 @olwe1 is this issue ready to get closed?

**Comment by olwe1** [comment]
Yep, removing `./ipfs_w` and run the app again works for me 🙂

**Comment by geolffreym** [comment]
@all-contributors please add @olwe1 for bug

**Comment by geolffreym** [comment]
@all-contributors please add @Stake2  for bug

**Comment by geolffreym** [comment]
@all-contributors please add @Stake2  for bug
