### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by Rxann** [ZorrillosDev/watchit-app#159]
Hi,
I am trying to use the web app but it seems to be stuck on connecting. Is there any fix for this?

**Comment by geolffreym** [comment]
Hey @Rxann, thank you for submitting and issue with us. Let me check and I will be back to you asap.

**Comment by Rxann** [comment]
Thank you

**Comment by geolffreym** [comment]
Sorry for delayed response. Could you try with this key => `zdpuAmM3fnwFhpDu4rV8ChxjRQe1SEiuaH7n9wurbewkhx7sz` please :). Thankl you @Rxann

**Comment by Rxann** [comment]
Ok, let me try that and get back to you.

**Comment by Rxann** [comment]
@geolffreym Hi, I just tested the key and it works!

**Comment by Rxann** [comment]
Also, It says I have 1 peer, is this normal?

**Comment by Rxann** [comment]
@geolffreym 
I am currently using discord

**Comment by geolffreym** [comment]
sure, let me know you user :) . is this solved already?

**Comment by Rxann** [comment]
@geolffreym 

Ok, my user is Rxan#1025.
I think the stuck on connecting part is solved.
