### ISSUE TITLE
Hosting A Worker Node

### ISSUE THREAD

**Issue by Rxann** [ZorrillosDev/watchit-app#160]
Hi, I would like to contribute to the community and host a worker node on my laptop.
Is there a guide on how to do this? 
If not I can make a PR if a dev sends me instructions!

**Comment by geolffreym** [comment]
@Rxann hello!! Sure, I am preparing a set of instruction to help you with this!!

**Comment by Rxann** [comment]
@geolffreym 
Ok! Thank you! I am looking forward to contributing!
You can @ me or contact me when this is released so I know but I will be sure to keep checking!

**Comment by geolffreym** [comment]
Sure @Rxann. I just sent an invite to your discord user :)
