### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by jadsongmatos** [ZorrillosDev/watchit-app#45]
Would you have the option to create an Android version using React ?

**Comment by geolffreym** [comment]
hi, thanks for creating an issue @Slender1808. Yes, we love the idea of having the mobile app, it would be great. We are currently adding multi-environment support to our code, to facilitate reuse of the application core. And of course we always listen to the opinions and demands of the community. We are open to new ideas and contributions :) .. 🚀

**Comment by geolffreym** [comment]
do you have any idea in mind @Slender1808 ? :)

**Comment by voitekthis** [comment]
You mean we can download it on android like Apk file?
Thanks for the hard work

**Comment by Slender1808** [comment]
> do you have any idea in mind @Slender1808 ? :)

it would be interesting to create a mobile repository

**Comment by geolffreym** [comment]
@voitekthis The plan is that it can be run in all possible environments and we consider that very soon with the help of the community we will have a mobile version ready, I just added a triage for the mobile project, you can see it and know a little about the priorities and monitor development

**Comment by geolffreym** [comment]
@Slender1808 the [repository](https://github.com/ZorrillosDev/watchit-app) exists only that we have not written anything yet XD. But I just created a [triage](https://github.com/orgs/ZorrillosDev/projects/2) with some of the priorities oriented to the development of the mobile application.

**Comment by Kohoshi12** [comment]
Besides the issue being about Android, the Linux mobile experience should be considered. Will be more simple to have a proper scaling of the program on mobile screens, which is a common problem for Linux programs.

**Comment by Slender1808** [comment]
netflix interface would be a good reference
