### ISSUE TITLE
Weird scrollbar behaviour in non fullscreen

### ISSUE THREAD

**Issue by justicenode** [ZorrillosDev/watchit-app#55]
For some reason the last row of movies doesnt get displayed properly and the scrollbar goes outside the window. Seems to work fine in fullscreen.

https://user-images.githubusercontent.com/26402137/116011396-14544580-a625-11eb-84ed-2c3b111cb820.mp4

OS: Win 10 | version 1909 | Build 18363.1379
Watchit version: 0.1.0-beta.8

If you need more info just let me know.

**Comment by geolffreym** [comment]
@all-contributors please add @justicenode  for ideas, bug, userTesting

**Comment by geolffreym** [comment]
@all-contributors please add @justicenode for ideas, bug, userTesting

**Comment by geolffreym** [comment]
@Jadapema could you help us to check this issue :) please

**Comment by Jadapema** [comment]
of course, fixing :)

**Comment by geolffreym** [comment]
@all-contributors please add @Farickmenacode73  for ideas, platform , userTesting.
