### ISSUE TITLE
multiple languages

### ISSUE THREAD

**Issue by Slender1808** [ZorrillosDev/watchit-app#75]
I was analyzing here it would be very useful to have a player that loads the audio separately from the image in this way if someone is watching something in another language you don't need to create another video just to have other audio options

**Comment by geolffreym** [comment]
Hi @Slender1808 thanks for submit and issue with us. Yeah, actually HLS help us with that, we can change the audio in playback without needing to load another video.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English (English)",DEFAULT=NO,AUTOSELECT=NO,URI="audio/audio_1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="jp",NAME="Japanese (Japanese)",DEFAULT=NO,AUTOSELECT=NO,URI="audio/audio_2.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English ()",FORCED=NO,AUTOSELECT=NO,URI="subtitle/sub_3.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English ()",FORCED=NO,AUTOSELECT=NO,URI="subtitle/sub_4.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=1400000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=842x480,AUDIO="aac",SUBTITLES="subs"
video/480p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2800000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac",SUBTITLES="subs"
video/720p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac",SUBTITLES="subs"
video/1080p.m3u8
```

**Comment by Slender1808** [comment]
sorry I didn't know about the existence of HLS where I get more information about it

**Comment by geolffreym** [comment]
Its ok buddy!! thanks for your initiative!!!

**Comment by Slender1808** [comment]
> Hi @Slender1808 thanks for submit and issue with us. Yeah, actually HLS help us with that, we can change the audio in playback without needing to load another video.
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English (English)",DEFAULT=NO,AUTOSELECT=NO,URI="audio/audio_1.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="jp",NAME="Japanese (Japanese)",DEFAULT=NO,AUTOSELECT=NO,URI="audio/audio_2.m3u8"
> #EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English ()",FORCED=NO,AUTOSELECT=NO,URI="subtitle/sub_3.m3u8"
> #EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English ()",FORCED=NO,AUTOSELECT=NO,URI="subtitle/sub_4.m3u8"
> #EXT-X-STREAM-INF:BANDWIDTH=1400000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=842x480,AUDIO="aac",SUBTITLES="subs"
> video/480p.m3u8
> #EXT-X-STREAM-INF:BANDWIDTH=2800000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac",SUBTITLES="subs"
> video/720p.m3u8
> #EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac",SUBTITLES="subs"
> video/1080p.m3u8
> ```

Could you show where you got this information?
