### ISSUE TITLE
subscribe

### ISSUE THREAD

**Issue by jadsongmatos** [ZorrillosDev/watchit-app#76]
it would be interesting a way to subscribe to channels that publish list of videos, a suggestion via rss

**Comment by geolffreym** [comment]
yeah!!! would be nice, the content creators could use this RSS to promote their content..

**Comment by geolffreym** [comment]
@Slender1808 do you have any idea or proposal to implement this? Would be great make some "collection feed" or any content creator or producer can just add their playlist addresses there :)

**Comment by geolffreym** [comment]
@all-contributors please add @Slender1808 for ideas

**Comment by Slender1808** [comment]
A more practical way would be to have a central server that saves the playlist and provides a link to each playlist so that if the items in the playlist change the playlist link will still work

**Comment by Slender1808** [comment]
the principle would be similar to the dns service where the user queries a name is dns force hash from the most recent list of ipfs

**Comment by geolffreym** [comment]
hmm, sounds interesting .. In principle I think that IPNS could help to maintain a CID of the lists that are being updated and then be able to show them in a UI or directly in the application. To keep all this decentralized maybe we can explore https://scuttlebot.io/

**Comment by Slender1808** [comment]
> hmm, parece interessante .. Em princípio eu acho que o IPNS poderia ajudar a manter um CID das listas que estão sendo atualizadas e então ser capaz de mostrá-las em uma IU ou diretamente no aplicativo. Para manter tudo isso descentralizado, talvez possamos explorar https://scuttlebot.io/

I think IPNS will be discontinued

**Comment by Slender1808** [comment]
este servidor dns pode ser descentralizado, mas não sei como poderia estar dentro do blockchain.

**Comment by geolffreym** [comment]
"DNS server" could be a reverse match from a key=>value struct eg {"myfunmovies': "CID address"} stored even in DHT or scuttlebot, from where we can fetch this lists and show into a UI or the app itself. could u try to make some experiment? We could work on your proposal for a movie catalog monitor.
https://docs.ipfs.io/reference/cli/#ipfs-dht

**Comment by Slender1808** [comment]
if key value change dht does not change too?

**Comment by Slender1808** [comment]
it can be a folder with several files where the file name would be the key myfunmovies and the value would be what was inside the file the CID address.

a way to do this would be through a folder at [syncthing](https://syncthing.net/)

**Comment by geolffreym** [comment]
yeah!! sounds good, lets try it!!

**Comment by geolffreym** [comment]
i think we can call to this "oracle" or "channel radar" ..

**Comment by Slender1808** [comment]
I did not understand

**Comment by geolffreym** [comment]
your idea is a place where everyone can go and check the current channels or playlist of movies correct? Well we could call it oracle or channel radar

**Comment by Slender1808** [comment]
got it, good idea, do you use any messaging app?

**Comment by geolffreym** [comment]
watchit:matrix.org

**Comment by Slender1808** [comment]
> watchit:matrix.org

add me from whatsapp (51) 93505-1715

**Comment by geolffreym** [comment]
hmm would u add me to matrix or share your matrix channels? mine is: @geolffrey:matrix.org

**Comment by Slender1808** [comment]
you could use hyperdrive to keep the list updated with the playlist.
[hyperdrive](https://hypercore-protocol.org/) is p2p protocol used in browser [beaker browser](https://beakerbrowser.com/)

**Comment by aphelionz** [comment]
Hi @Slender1808 I love this idea. What do you think about creating some sort of prototype for it?

As for the p2p protocol, we're already using OrbitDB so it might be simplest just to subscribe to those pubsub channels

**Comment by Slender1808** [comment]
I have to study about orbitdb never used it before

**Comment by aphelionz** [comment]
Sure, just let us know :)
