### ISSUE TITLE
No loading image in Ubuntu 20.04

### ISSUE THREAD

**Issue by mathiassond** [ZorrillosDev/watchit-app#87]
![Screenshot from 2021-07-04 12-28-24](https://user-images.githubusercontent.com/49319141/124381587-9024db00-dcc3-11eb-8eae-c605fe7dc5db.png)

images doesn't load:(

**Comment by geolffreym** [comment]
Hi @mathiassond thank you for submit an issue. Is this issue persisting after logout and re-login?

**Comment by mathiassond** [comment]
yes it persist, its been tried:)

**Comment by mathiassond** [comment]
By the way, what has happened the the site, I'm not able to reach it anymore? :(
![Screenshot from 2021-07-07 21-03-51](https://user-images.githubusercontent.com/49319141/124815052-0f860900-df67-11eb-9e63-0094d009ae3f.png)

**Comment by geolffreym** [comment]
Hey @mathiassond could you try one more time please. All should be working now!!

**Comment by mathiassond** [comment]
Sorry but it seem to remain

**Comment by geolffreym** [comment]
@mathiassond maybe using this key please? 
k2k4r8kghdt2njykw7n5bisp4wgynjhs4gnnh5p1ik2ixqdive47o0oa

**Comment by mathiassond** [comment]
it say the key is invalid.

**Comment by geolffreym** [comment]
this ll be fixed on v0.2.0 release @mathiassond

**Comment by mathiassond** [comment]
Okay, thanks <3

Geolffrey Mena ***@***.***> skrev: (10 juli 2021 20:25:42 CEST)
>this ll be fixed on v0.2.0 release @mathiassond 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ZorrillosDev/watchit-app/issues/87#issuecomment-877682195

-- Skickat från /e/ Mail.

**Comment by geolffreym** [comment]
Fixed in 0.2.0 release

**Comment by geolffreym** [comment]
@all-contributors please add @mathiassond for userTesting, bug
