### ISSUE TITLE
request: distribute via Flatpak

### ISSUE THREAD

**Issue by LongJohn-Silver** [ZorrillosDev/watchit-app#93]
Title, basically, it would be nice to have a more distro agnostic distribution model which is not AppImage and which has some degree of isolation.

**Comment by LongJohn-Silver** [comment]
Bump.

**Comment by geolffreym** [comment]
Hi @LongJohn-Silver , thanks for reaching out and let us know your issue. We have been working in a "Improvements Proposal" repo, we would love to see some suggestions on this use case :)
https://github.com/ZorrillosDev/WEISP

**Comment by LongJohn-Silver** [comment]
Imo it is better to keep everything under its own repo to avoid confusions, but I will duplicate this issue if needed.

**Comment by xirapo** [comment]
@LongJohn-Silver We can work on packaging the application on Flatpack.

**Comment by LongJohn-Silver** [comment]
I only know a bit of web programming, very little, I am not a developer, so I don't know how much technical knowledge is needed to package this as a flatpak, I could try and read the docs and see how hard it is, it's good knowledge anyway, but can't make any promises. :/
